src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 * @Gedmo\Tree(type="nested")
 * @ORM\Table(name="category")
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @Gedmo\TreeLeft
     * @ORM\Column(type="integer")
     */
    private $lft;

    /**
     * @Gedmo\TreeRight
     * @ORM\Column(type="integer")
     */
    private $rgt;

    /**
     * @Gedmo\TreeRoot
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(name="tree_root", referencedColumnName="id", onDelete="CASCADE")
     */
    private $root;

    /**
     * @Gedmo\TreeLevel
     * @ORM\Column(name="lvl", type="integer")
     */
    private $lvl;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="Children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $Parent;

    /**
     * @ORM\OneToMany(targetEntity=Category::class, mappedBy="Parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $Children;

    /**
     * @ORM\OneToMany(targetEntity=Product::class, mappedBy="Category")
     */
    private $products;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active = true;

    /**
     * @Gedmo\SortablePosition
     * @ORM\Column(name="position", type="integer")
     */
    private $position;

    public function __construct()
    {
        $this->Children = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name ?? '-';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->Parent;
    }

    public function setParent(?self $Parent): self
    {
        $this->Parent = $Parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getChildren(): Collection
    {
        return $this->Children;
    }

    public function addChild(self $child): self
    {
        if (!$this->Children->contains($child)) {
            $this->Children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(self $child): self
    {
        if ($this->Children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getLft(): ?int
    {
        return $this->lft;
    }

    public function setLft(int $lft): self
    {
        $this->lft = $lft;

        return $this;
    }

    public function getRgt(): ?int
    {
        return $this->rgt;
    }

    public function setRgt(int $rgt): self
    {
        $this->rgt = $rgt;

        return $this;
    }

    public function getLvl(): ?int
    {
        return $this->lvl;
    }

    public function setLvl(int $lvl): self
    {
        $this->lvl = $lvl;

        return $this;
    }

    public function getRoot(): ?self
    {
        return $this->root;
    }

    public function setRoot(?self $root): self
    {
        $this->root = $root;

        return $this;
    }

    public function getHierarchyList(): string
    {
        return str_repeat("_", $this->lvl * 2) . $this->name;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php
namespace App\Controller;

use App\Entity\Comment;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Node\Expression\Test\NullTest;

class DefaultController extends AbstractController
{
    const PAGE_NOT_EXIST = 'default/page-not-exist.html.twig';

    public function index(EntityManagerInterface $em, Request $request): Response
    {
        $cr = $em->getRepository('App:Category');

        $categories = $cr->findAll();
        //\var_dump($categories); exit;

        return $this->render('default/index.html.twig', [
            'categories' => $categories,
        ]);
    }

    /**
     * Get Category with id or first category if id is null
     *
     * @param mixed $id int or null
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    public function category($id = null, EntityManagerInterface $em, Request $request): Response
    {
        $fields = ['id'=>$id, 'active'=>true];
        if (is_null($id))     
            unset($fields['id']);

        $category = $em->getRepository('App:Category')->findOneBy($fields,null,1);

        return $this->render(
            ($category ? 'default/category.html.twig' : self::PAGE_NOT_EXIST), [
            'category' => $category,
            'id' => $id,
            'type' => 'Category',
            'viewType' => $request->get('viewType','grid'),
            'itemsPerPage' =>  $request->get('itemsPerPage',25),
            'currentPage' => $request->get('currentPage',1),
            'orderBy' => $request->get('orderBy','id'),
            'orderType' => $request->get('orderType','ASC')    
        ]);
    }
    

    public function getProducts(int $categoryId, EntityManagerInterface $em): Response
    {
        
        $products = $em->getRepository('App:Category')->findOneBy(['id'=>$categoryId]);

        return $this->render('default/products.html.twig', [
            'products'=>$products->getProducts()
        ]);
    }
    
    /**
     * Get all products in category
     * 
     * @param int|null $categoryId Category id
     * @param string $view Twig file
     * @param int $offset Page Number
     * @param int $limit Items Per Page
     * @param string $orderBy Order field
     * @param string $orderType Order direction ASC | DESC
     * @return Response
     */
    public function getAllProductsInCategory($categoryId, string $view, int $offset = 0, int $limit = 0, string $orderBy = 'id', string $orderType = 'ASC', string  $viewType='grid'): Response
    {       
        $em = $this->getDoctrine()->getManager();
        
        $curID = [$categoryId];
        //$subcats = [];
        if ((null !== $categoryId) && ($categoryId !== 'all')) {
            $cat = $em->getRepository('App:Category')->findOneBy(['id'=>$categoryId]);
            $subcats = $em->getRepository('App:Category')->getAllSubCategories($categoryId,$cat->getRoot()->getId(),$cat->getLft(),$cat->getRgt());
            $subcats = \array_merge($curID, \array_column($subcats,'id'));
            $productsRes = $em->getRepository('App:Product')
                    ->findAllProductsInCategory($subcats, $offset, $limit, $orderBy, $orderType);
            //int $offset = 0, int $limit = 0, string $orderBy = 'id', string $orderType = 'ASC'
        } else
            {
                $productsRes['query'] = $em->getRepository('App:Product')->findBy(['active'=>true]);
                $productsRes['totalCount'] = count($productsRes['query']);
                if ($limit > 0) {
                    $productsRes['query'] = $em->getRepository('App:Product')->findBy(
                        [
                            'active'=>true
                        ]
                        ,null,
                        $limit, $offset*$limit);
                }
            }

        $result = [
            'products' => $productsRes['query'],
            'limit' => $limit,
            'totalCount' => $productsRes['totalCount'],
            'currentPage' => ($offset+1),
            'showFrom' => ($limit * $offset + 1),
            'viewType' => $viewType,
            'showTo' => ($limit>0 ? ($limit*($offset+1)) : $productsRes['totalCount']),
            'orderBy' => $orderBy,
            'orderType' => $orderType,
            //'subcats' => json_encode($subcats,JSON_UNESCAPED_UNICODE)
        ];

        return $this->render($view, $result);
        
    }

    /**
     * @Route("/all-products", name="all_products", methods={"POST"}) 
     * 
     */
    public function getAllProductsAjax(Request $request): Response
    {
        return $this->getAllProductsInCategory(
            $request->get('categoryId',null),
            $request->get('view',''),
            $request->get('offset',0),
            $request->get('limit',0),
            $request->get('orderBy','id'),
            $request->get('orderType','asc'),
            $request->get('viewType','grid'),
        );
    }
    
    public function getCategories(string $view, $parent=null, int $limit=0, EntityManagerInterface $em): Response
    {
        $categories = $em->getRepository('App:Category')->findBy(
            ['active'=>true, 'Parent'=>$parent],
            null,
            ($limit===0 ? null : $limit)
        );

        return $this->render($view, [
            'categories' => $categories
        ]);
    }

    public function getSubCategories(EntityManagerInterface $em,$parent=null)
    {
        $categories = $em->getRepository('App:Category')->findBy([
            'active'=>true, 'Parent'=>$parent]);

        return $this->render('default/subcategories.html.twig', [
            'categories' => $categories            
        ]);
    } 

    /**
     * Get Categories Path (breadcrumbs) for category id
     *
     * @param int|null $id Category id
     * @param boolean $isProductPage if true - this is product page
     * @param boolean $addLi if true - add <li> tags
     * @return string
     */
    public function getCategoriesPath($id=null, bool $isProductPage=false, bool $addLi=false)
    {
        $path = [];
        $liStart = $liEnd = "";
        $separator = " / ";
        if (true === $addLi) {
            $liStart = "<li>";
            $liEnd = "</li>";
            $separator="";
        }
        $em = $this->getDoctrine()->getManager();
        $current = $em->getRepository('App:Category')->findOneBy([
            //'active'=>true,
            'id'=>$id
        ]);

        if ($isProductPage) {
            $url = $this->generateUrl('category',['id'=>$current->getId()]);
            $path[] = $liStart . "<a href=$url >".(string) $current . "</a>" . $liEnd;
        }

        while($current)
        {
            $current = $current->getParent() ? 
                $em->getRepository('App:Category')->findOneBy([
                //'active'=>true,
                'id'=>$current->getParent()
                ])
                : null;

            if ($current)
            {
                $url = $this->generateUrl('category',['id'=>$current->getId()]);
                array_unshift($path,$liStart . "<a href=$url >".(string) $current . "</a>" . $liEnd);
            }
        }  
        
        return new Response(implode($separator, $path) . $separator);
    }
    
    /**
     * Get new products function
     *
     * @param EntityManagerInterface $em
     * @param integer $days The number of days after receipt in which the product must be considered new
     * @return Response
     */
    public function getNewArrivalProducts(EntityManagerInterface $em, int $days=30)
    {
        $products = $em->getRepository('App:Product')->findNewProducts($days);
        //SELECT * FROM `product` WHERE created BETWEEN NOW() - INTERVAL 2 DAY AND NOW(); 
        return $this->render('default/layouts/parts/single-product.html.twig', [
            'products' => $products,
            'labels' => [
                ['class'=>'new', 'name'=>'New']
            ]
        ]);
    }

    public function getProductRating(int $product_id, string $addonClass, EntityManagerInterface $em)
    {
        $rating = $em->getRepository('App:Comment')->getAverageRating($product_id);
        //SELECT * FROM `product` WHERE created BETWEEN NOW() - INTERVAL 2 DAY AND NOW();
        return $this->render('default/layouts/parts/rating-stars.html.twig', [
            'rating'=>(count($rating)>0 ? (int)round($rating[0]['avgRate'],0) : 0),
            'addonClass' => $addonClass
        ]); 
    }

    /**
     * Get Random Products function
     *
     * @param EntityManagerInterface $em
     * @param integer $limit Limit of products
     * @return Response
     */
    public function getRandomProducts(EntityManagerInterface $em, int $limit=5): Response
    {
        $products = $em->getRepository('App:Product')->findRandProducts($limit);
        //SELECT * FROM `product` WHERE created BETWEEN NOW() - INTERVAL 2 DAY AND NOW(); 
        return $this->render('default/layouts/parts/single-product.html.twig', [
            'products' => $products,
            'labels' => [
            ]
        ]);
    }

    public function getViewsCount(string $template, int $currentItemsPerPage = 25): Response
    {
        return $this->render($template,[
            'pages' => [5,10,15,20,25],
            'current' => $currentItemsPerPage
        ]
        );
    }

    public function getPagination(string $template='', int $currentPage=1, int $limit=10, int $itemsCount=0): Response
    {
        if ($template === '')
            $template = 'default/layouts/parts/categories/categories-pagination.html.twig';
        
        if ($limit > 0)
            $maxPages = (int) ceil($itemsCount / $limit);
        else
            $maxPages = 1;
        /*

templates/default/cart.html.twig
{% extends "base.html.twig" %}

{% block title %} Cart - {{ title }} {% endblock %}

{% block body %}

    <!--breadcumb area start -->
    <div class="breadcumb-area overlay pos-rltv">
        <div class="bread-main">
            <div class="bred-hading text-center">
                <h5>Cart Details</h5> </div>
            <ol class="breadcrumb">
                <li class="home"><a title="Go to Home Page" href="/">Home</a></li>
                <li class="active">Cart</li>
            </ol>
        </div>
    </div>
    <!--breadcumb area end -->
    <!--cart-checkout-area start -->
    
    <div class="cart-checkout-area  pt-30">
        <div class="container">
        <div class="row">
            <div class="product-area">
                <div class="title-tab-product-category">
                    <div class="col-md-12 text-center pb-60">
                        <ul class="nav heading-style-3" role="tablist">
                            <li role="presentation" class="{% if progress == 'cart' %} active {% endif %} shadow-box"><a href="#cart" aria-controls="cart" role="tab" data-toggle="tab"><span>01</span> Shopping cart</a></li>
                            <li role="presentation" class="{% if progress == 'checkout' %} active {% endif %} shadow-box"><a href="#checkout" aria-controls="checkout" role="tab" data-toggle="tab"><span>02</span>Checkout</a></li>
                            <li role="presentation" class="{% if progress == 'pay' %} active {% endif %} shadow-box"><a href="#complete-order" aria-controls="complete-order" role="tab" data-toggle="tab"><span>03</span> complete-order</a></li>
                        </ul>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-sm-12">
                    <div class="content-tab-product-category pb-70">
                        <!-- Tab panes -->
                        <div class="tab-content">
                            <!-- Tab panel Cart -->
                            {{ include('default/layouts/cart-layout.html.twig') }}
                            <!-- Tab panel Checkout -->
                            {{ include('default/layouts/cart-checkout.html.twig') }}
                            <!-- Tab panel Checkout-complete -->
                            {{ include('default/layouts/cart-complete-order.html.twig') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>                                  
    </div>

  <script src="{{ asset('js/vendor/jquery-1.12.0.min.js') }}"></script>
  <script src="{{ asset('js/cart-common.js') }}"></script>
    <!--cart-checkout-area end-->

{% endblock %}

templates/default/category.html.twig
{% extends "base.html.twig" %}

{% block title %} {% if id %} {{ category.name }} {% else %} All Categories {% endif %} {% endblock %}

{% block body %} 

   
  {% set breadcrumbTitle = 'Categories' %}
  {% set isProductPage = false %}
  {{ include('default/layouts/parts/product/product-breadcrumbs.html.twig') }}
    
  <!--shop main area are start-->
  <div class="shop-main-area ptb-70">
    <div class="container">
      <div class="row">
        {{ include('default/layouts/sidebar.html.twig') }}
        <!--main-shop-product start-->
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div class="shop-wraper">
            {{ render(controller(
              'App\\Controller\\DefaultController::getAllProductsInCategory',
              {
                'categoryId': id, 
                'view': 'default/layouts/category-main.html.twig',
                'limit': itemsPerPage,
                'offset': (currentPage-1),
                'viewType': viewType,
                'orderBy': orderBy,
                'orderType': orderType
              }
              ))
            }}
          </div>
        </div>
        <!--main-shop-product start-->
      </div>
    </div>
  </div>

{% endblock %}

templates/default/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Home || Clothing{% endblock %}

{% block body %}

    {{ include('default/layouts/slider.html.twig') }}

    {{ include('default/layouts/delivery.html.twig') }}
{#
    {{ include('default/layouts/branding.html.twig') }}

#}
    {{ include('default/layouts/new-arrival.html.twig') }}
{#
    {{ include('default/layouts/banner.html.twig') }}

    {{ include('default/layouts/discount-features-onsale.html.twig') }}

    {{ include('default/layouts/testimonial.html.twig') }}

    {{ include('default/layouts/brand.html.twig') }}

    {{ include('default/layouts/blog.html.twig') }}
#}

{% endblock %}

templates/default/leftsidebar.html.twig
<ul>
    {% for category in categories %}
        <li>
            <a href={{ path('category', {id:category.id}) }}>{{ category.name }} [{{category.products|length}}]</a>
            {{ render(controller(
                'App\\Controller\\DefaultController::getCategories',{'parent':category.id}))
            }}            
        </li>
    {% endfor %}
</ul> 

templates/default/page-not-exist.html.twig
{% extends "base.html.twig" %}
{% block title %} {{ type }} {{ id }} not exist {% endblock %}
{% block body %}
    <div class="alert alert-danger" role="alert">
        {{ type }} {{ id }} not exist
    </div>
{% endblock %}

templates/default/product.html.twig
{% extends "base.html.twig" %}

{% block title %} {{ product.name }} {% endblock %}

{% block body %}

    {% set breadcrumbTitle = 'Product Details' %}
    {% set isProductPage = true %}
    {{ include('default/layouts/parts/product/product-breadcrumbs.html.twig') }}

    <!--single-portfolio-area are start-->
    <div class="single-protfolio-area ptb-70">
        <div class="container">
            <div class="row">
                <div class="col-md-7 col-sm-12 col-xs-12">
                   {{ include('default/layouts/product-image-area.html.twig') }}
                </div>
                <div class="col-md-5 col-sm-12 col-xs-12">
                   {{ include('default/layouts/product-description-area.html.twig') }}
                </div>
            </div>  
        </div>
    </div>
    <!--single-portfolio-area are start-->

    {{ include('default/layouts/product-tabs-area.html.twig') }}
    
    {{ include('default/layouts/new-arrival.html.twig') }}
    
{% endblock %}

templates/default/products.html.twig
{% if products | length > 0 %}
    <ul>
        {% for product in products %}
            <li> <a href={{ path('product', {id:product.id}) }}>{{ product.name }}</a> </li>            
        {% endfor %}
    </ul>
{% endif %} 

templates/default/subcategories.html.twig
<div class="row">
    {% for category in categories %}
        <div class="col-md-5 text-center pb-4">
            <a href={{ path('category', {id:category.id}) }}>

                <img src="https://fakeimg.pl/200/?text={{ category.name }}">
                <div>
                    {#{{ category.name }}#}
                    <div>
                        Subcategories count: {{category.children|length}}
                    </div>
                    <div>
                        Current category products count: {{category.products|length}}
                    </div>
                </div>
            </a>
        </div>       

    {% endfor %}
</div>